[package]
name = "add"
version = "0.1.0"
edition = "2024"

[dependencies]
cargo-llvm-cov = "0.6.17"
tokio = { version = "1.37", features = ["full"] }
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mockito = "1.4"
